const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Function,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Acts.RotateClockwise,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.JavaScriptInEvents.Es_game_Event65_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.CallFunction
	];
};
self.C3_JsPropNameTable = [
	{gol: 0},
	{shoot: 0},
	{verify: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Physics: 0},
	{Fade: 0},
	{ball: 0},
	{arrow: 0},
	{direct: 0},
	{direct2: 0},
	{Touch: 0},
	{Pin: 0},
	{angulo: 0},
	{Trave: 0},
	{Bg: 0},
	{campo: 0},
	{campo2: 0},
	{campo3: 0},
	{bar_back: 0},
	{barradeForca: 0},
	{colisionRed: 0},
	{colisionYellow: 0},
	{colisionBlue: 0},
	{Solid: 0},
	{ground_phisic: 0},
	{horizontal: 0},
	{vertical: 0},
	{target: 0},
	{Smoke: 0},
	{boom: 0},
	{control_bar: 0},
	{star_: 0},
	{golkeper: 0},
	{board: 0},
	{life_hud: 0},
	{verification: 0},
	{Function: 0},
	{direction: 0},
	{Audio: 0},
	{torcida: 0},
	{flash: 0},
	{Sine: 0},
	{title: 0},
	{info: 0},
	{animation_menu: 0},
	{ball_menu: 0},
	{play: 0},
	{Sprite2: 0},
	{inf: 0},
	{hand: 0},
	{Sprite4: 0},
	{splash_ngstudios: 0},
	{hud_score: 0},
	{Black_gameOver: 0},
	{gameOver: 0},
	{menu: 0},
	{retry: 0},
	{LocalStorage: 0},
	{txt_info: 0},
	{txt_points_display: 0},
	{txt_debug: 0},
	{Fade2: 0},
	{NG_STUDIO: 0},
	{highscore: 0},
	{GameOver: 0},
	{GameOn: 0},
	{touching: 0},
	{heightBar: 0},
	{powerUp: 0},
	{life: 0},
	{score: 0},
	{ballY: 0},
	{ballX: 0},
	{speed_rotate: 0},
	{velocidade: 0},
	{ultima_puntuacion: 0},
	{force: 0},
	{lsName: 0},
	{sound: 0}
];

self.InstanceType = {
	gol: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	direct: class extends self.ISpriteInstance {},
	direct2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	angulo: class extends self.ISpriteInstance {},
	Trave: class extends self.ISpriteInstance {},
	Bg: class extends self.ISpriteInstance {},
	campo: class extends self.ISpriteInstance {},
	campo2: class extends self.ISpriteInstance {},
	campo3: class extends self.ISpriteInstance {},
	bar_back: class extends self.ISpriteInstance {},
	barradeForca: class extends self.ISpriteInstance {},
	colisionRed: class extends self.ISpriteInstance {},
	colisionYellow: class extends self.ISpriteInstance {},
	colisionBlue: class extends self.ISpriteInstance {},
	ground_phisic: class extends self.ISpriteInstance {},
	target: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	boom: class extends self.ISpriteInstance {},
	control_bar: class extends self.ISpriteInstance {},
	star_: class extends self.ISpriteInstance {},
	golkeper: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	life_hud: class extends self.ISpriteInstance {},
	verification: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	direction: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	torcida: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	animation_menu: class extends self.ISpriteInstance {},
	ball_menu: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inf: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	splash_ngstudios: class extends self.ISpriteInstance {},
	hud_score: class extends self.ISpriteInstance {},
	Black_gameOver: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	txt_info: class extends self.ITextInstance {},
	txt_points_display: class extends self.ITextInstance {},
	txt_debug: class extends self.ITextInstance {},
	NG_STUDIO: class extends self.ISpriteInstance {}
}